### ISSUE TITLE
Vibration cannot be set to `false`

### ISSUE THREAD

**Issue by jpmc** [its-shivam/patternLock.js#1]
Here: https://github.com/its-shivam/patternLock.js/blob/master/src/patternlock.js#L10

```
this.vibrate = config.vibrate || true;
```

For the integer parts in the other variables, any value other than zero would evaluate to true and short circuit, allowing you to keep the number if provided. But for `config.vibrate` it expects a boolean.

So if I pass `vibrate = false` then `false || true` would override my preference and return `true` anyway.

You would need to check if undefined first before assuming a default. I can recommend an alternative.

```
this.vibrate = (config.vibrate === undefined) ? true : config.vibrate;
```

This will assume true if it wasn't provided, or else keep the boolean that was passed in (be it true or false).

**Comment by ishiv01** [comment]
Thanks for finding the issue, i have changed the code as per your suggestion.
